languageCode = 'es-ar'
title = 'drkbugs'
defaultContentLanguage = "es"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = "drkbugs"

theme = "minimo"

disqusShortname = "drk"
googleAnalytics = "UA-29993798-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"
posts = "/:slug"

[params.info]
description = "Software engineering"
title404 = "404 - Not found"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "drkbugs"
startYear = "2002"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page","legacy"] # boolean / array of sections
hideEntryMeta = ["page","legacy"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud","translations"]
footer = ["social_menu","i18nlist"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "drkblog" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "drkbugs"
email = "webmaster@drk.com.ar"
#facebook = "drkbugs"
github = "drkblog"
#gitlab = "drkbugs"
#instagram = "drkbugs"
#linkedin = "muniftanjim"
twitter = "drkblog"
#telegram = "drkbugs"
#google_scholar = "qc6CJjYAAAAJ"
youtube = "UClPU76FC8TBftSAGFlay36g"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "drkbugs"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "drkbugs"
repository = "minimo"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/drkbugs/minimo"

[blackfriday]
hrefTargetBlank = true

[languages]
  [languages.es]
    languageName = "Español"
    description = "Ingeniería de software"
    weight = 1
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Inicio"
        url = "/"
        weight = 1
      [[languages.es.menu.main]]
        name = "Artículos"
        url = "/posts/"
        weight = 2
      [[languages.es.menu.main]]
        name = "Legacy"
        url = "/legacy/"
        weight = 3
      [[languages.es.menu.main]]
        name = "Acerca de drkbugs"
        url = "/about/"
        weight = 4

  [languages.en]
    languageName = "English"
    description = "Software engineering"
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/en/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Posts"
        url = "/en/posts/"
        weight = 2
      [[languages.en.menu.main]]
        name = "Legacy"
        url = "/en/legacy/"
        weight = 3
      [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        weight = 4
